spring:
  application:
    name: shiying-govern-gateway

server:
  port: 8080
  servlet:
    context-path: /api

zuul:
  routes:
    service-auth:
      path: /auth/**
      serviceId: shiying-service-auth
      strip-prefix: false
      sensitiveHeaders:
    service-ucenter:
      path: /ucenter/**
      serviceId: shiying-service-ucenter
      strip-prefix: false
      sensitiveHeaders:
    service-supplier:
      path: /supplier/**
      serviceId: shiying-service-supplier
      strip-prefix: false
      sensitiveHeaders:
    service-Test_projects:
      path: /Test_projects/**
      serviceId: shiying-service-Test_projects
      strip-prefix: false
      sensitiveHeaders:
    service-drugs:
      path: /drugs/**
      serviceId: shiying-service-drugs
      strip-prefix: false
      sensitiveHeaders: