spring:
  application:
    name: shiying-govern-gateway

server:
  port: 8080
  servlet:
    context-path: /api

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 120000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

zuul:
  routes:
    service-auth:
      path: /auth/**
      serviceId: shiying-service-auth
      strip-prefix: false
      sensitiveHeaders:
    service-ucenter:
      path: /ucenter/**
      serviceId: shiying-service-ucenter
      strip-prefix: false
      sensitiveHeaders:
    shiying-service-drugs-supplier:
      path: /drugsSupplier/**
      serviceId: shiying-service-drugs-supplier
      strip-prefix: false
      sensitiveHeaders:
    shiying-service-activiti:
      path: /activiti/**
      serviceId: shiying-service-activiti
      strip-prefix: false
      sensitiveHeaders:
    service-supplier:
      path: /supplier/**
      serviceId: shiying-service-supplier
      strip-prefix: false
      sensitiveHeaders:
    service-drugs:
      path: /drugs/**
      serviceId: shiying-service-drugs
      strip-prefix: false
      sensitiveHeaders:
    service-patient:
      path: /patient/**
      serviceId: shiying-service-patient
      strip-prefix: false
      sensitiveHeaders:
    service-department:
      path: /department/**
      serviceId: shiying-service-department
      strip-prefix: false
      sensitiveHeaders:
    service-register:
      path: /register/**
      serviceId: shiying-service-register
      strip-prefix: false
      sensitiveHeaders:
    service-drugs_storage:
      path: /drugs_storage/**
      serviceId: shiying-service-drugs_storage
      strip-prefix: false
      sensitiveHeaders:
    service-electronic_case:
      path: /electronic_case/**
      serviceId: shiying-service-electronic_case
      strip-prefix: false
      sensitiveHeaders:
    service-drugs_purchase:
      path: /drugs_purchase/**
      serviceId: shiying-service-drugs_purchase
      strip-prefix: false
      sensitiveHeaders:
      service-drugs_purchase_detailed:
        path: /drugs_purchase_detailed/**
        serviceId: shiying-service-drugs_purchase_detailed
        strip-prefix: false
        sensitiveHeaders:

    service-users_department:
      path: /users_department/**
      serviceId: shiying-service-users_department
      strip-prefix: false
      sensitiveHeaders:

    service-test_correlation:
      path: /test_correlation/**
      serviceId: shiying-service-test_correlation
      strip-prefix: false
      sensitiveHeaders:
    service-test_projects:
      path: /test_projects/**
      serviceId: shiying-service-test_projects
      strip-prefix: false
      sensitiveHeaders:
    service-test_synthesize:
      path: /test_synthesize/**
      serviceId: shiying-service-test_synthesize
      strip-prefix: false
      sensitiveHeaders:
    service-test_correlationaffiliate:
      path: /test_correlationaffiliate/**
      serviceId: shiying-service-test_correlationaffiliate
      strip-prefix: false
      sensitiveHeaders:
    service-scheduling:
      path: /scheduling/**
      serviceId: shiying-service-scheduling
      strip-prefix: false
      sensitiveHeaders:
    service-icd:
      path: /icd/**
      serviceId: shiying-service-icd
      strip-prefix: false
      sensitiveHeaders:
    service-dms_drug_refund_item_record:
      path: /dms_drug_refund_item_record/**
      serviceId: shiying-service-dms_drug_refund_item_record
      strip-prefix: false
      sensitiveHeaders:
    service-dms_case_model:
      path: /dms_case_model/**
      serviceId: shiying-service-dms_case_model
      strip-prefix: false
      sensitiveHeaders:
    service-dms_case_model_catalog:
      path: /dms_case_model_catalog/**
      serviceId: shiying-service-dms_case_model_catalog
      strip-prefix: false
      sensitiveHeaders:
    service-us:
      path: /us/**
      serviceId: shiying-service-us
      strip-prefix: false
      sensitiveHeaders: