spring:
  application:
    name: shiying-service-activiti

server:
  port: 40800
  servlet:
    context-path: /activiti

activiti:
  database-schema: ACTIVITI
  database-schema-update: true
  history-level: full
  db-history-used: true