spring:
  application:
    name: shiying-govern-gateway

server:
  port: 8080
  servlet:
    context-path: /api

zuul:
  routes:
    service-auth:
      path: /auth/**
      serviceId: shiying-service-auth
      sensitiveHeaders:
      strip-prefix: false
    service-ucenter:
      path: /ucenter/**
      serviceId: shiying-service-ucenter
      sensitiveHeaders:
      strip-prefix: false