spring:
  application:
    name: shiying-service-activitis
  activiti:
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true

server:
  port: 40800
  servlet:
    context-path: /activiti
