spring:
  application:
    name: shiying-service-auth

server:
  port: 40400
  servlet:
    context-path: /auth

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: SyWebApp
  clientSecret: SyWebApp
  cookieDomain: localhost
  cookieMaxAge: -1

encrypt:
  key-store:
    location: classpath:/sy.keystore
    secret: shiyingkey
    alias: sykey
    password: shiying